from werkzeug.exceptions import BadRequest  # , Unauthorized
from ..db.models import Test
from .auth import auth


@auth()
def create(auth_user, body):
    breakpoint()
    print("hello!")
    try:
        test = Test.create(author=auth_user,
                           name=body.get('name'),
                           data=body.get('data'))
    except Exception as e:
        err_msg = str(e)
        print(e)
        raise BadRequest(f'Could not add test: {err_msg}') from e

    return test.to_obj(whos_asking=auth_user)
