from werkzeug.exceptions import BadRequest
from ..db.models import Test
from .auth import auth
from .util import get_test


@auth()
def create(auth_user, body):
    try:
        test = Test.create(author=auth_user,
                           name=body.get('name'),
                           data=body.get('data'))
    except Exception as e:
        err_msg = str(e)
        raise BadRequest(f'Could not add test: {err_msg}')

    return test.to_obj(whos_asking=auth_user)


@auth()
@get_test()
def detail(test, auth_user):
    return test.to_obj(whos_asking=auth_user)
